# -*- coding: utf-8 -*-
"""contact_book.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0HSIJJBhL89YjysAtqxSpRoweaUUIQo
"""

import json
def save_contacts():
  with open("contacts.json","w") as file:
    json.dump(contacts,file)
contacts={}
def load_contacts():
  global contacts
  try:
    with open("contacts.json","r") as file:
      contacts=json.load(file)
  except FileNotFoundError:
    contacts={}
def add_contacts():
  name=input("Enter contact name: ")
  phone=input("Enter phone number: ")
  email=input("Enter email address: ")
  contacts[name]={"phone":phone,"email":email}
  print("Contact added successfully!")
def view_contacts():
  if not contacts:
    print("No contacts found.")
    return
  for name,info in contacts.items():
    print("\nName:",name)
    print("phone:",info["phone"])
    print("email:",info["email"])
def search_contacts():
  name=input("Enter contact name to search: ")
  if name in contacts:
    print("Phone:",contacts[name]["phone"])
    print("Email:",contacts[name]["email"])
  else:
    print("Contact not found.")
def update_contacts():
  name=input("Enter contact name to update: ")
  if name in contacts:
    phone=input("Enter new phone number: ")
    email=input("Enter new email address: ")
    contacts[name]["phone"]=phone
    contacts[name]["email"]=email
    print("Contact updated successfully!")
  else:
    print("Contact not found.")
def delete_contacts():
  name=input("Enter contact name to delete: ")
  if name in contacts:
    del contacts[name]
    print("Contact deleted successfully!")
  else:
    print("Contact not found.")
load_contacts()
while True:
  print("\nContact Book")
  print("1.Add Contact")
  print("2.View Contact")
  print("3.Search Contact")
  print("4.Update Contact")
  print("5.Delete Contact")
  print("6.Exit")
  choice=input("Enter your choice:")
  if choice=="1":
    add_contacts()
  elif choice=="2":
    view_contacts()
  elif choice=="3":
    search_contacts()
  elif choice=="4":
    update_contacts()
  elif choice=="5":
    delete_contacts()
  elif choice=="6":
    save_contacts()
    print("Contacts saved.Goodbye!")
    break
  else:
    print("Invalid choice")

